### ISSUE TITLE
Seemingly strange instanceOf behavior with union of errors

### ISSUE THREAD

**Issue by joshgummersall** [gvergnaud/ts-pattern#63]
**Describe the bug**

Trying to match the following error union type:
<img width="1265" alt="Screen Shot 2021-12-08 at 12 24 35 PM" src="https://user-images.githubusercontent.com/1235378/145279235-98ee08dc-8507-4f2a-9f76-5cebdb27f8a6.png">

I'd expect each `with(instanceOf` to properly narrow `err`, but instead I'm seeing strange types in the handler functions:
<img width="1306" alt="Screen Shot 2021-12-08 at 12 25 05 PM" src="https://user-images.githubusercontent.com/1235378/145279242-0fcc90d0-24e6-45ad-83c0-aefe956ecf79.png">

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/s/keen-tesla-jciu2?file=/src/index.ts

**Versions**
- TypeScript version: 4.5.2
- ts-pattern version: 3.3.3
- environment: node v14.17.4

**Comment by gvergnaud** [comment]
Thanks for the report, I fixed it in [this commit](https://github.com/gvergnaud/ts-pattern/commit/7c3af7273daceb5fdae2dde31eff28d4f9870017), I'll followup with a patch release shortly!

**Comment by joshgummersall** [comment]
@gvergnaud amazing! Thanks for resolving.

**Comment by joshgummersall** [comment]
I cloned the repo, built it locally, and linked it with my test project. I see the runtime execution is working, but I'm still seeing handlers typed as a union of errors. Attached a quick screenshot of Intellisense in VSCode:

<img width="848" alt="Screen Shot 2021-12-15 at 5 54 59 PM" src="https://user-images.githubusercontent.com/1235378/146293797-10643290-e0fd-4a20-8d48-a0e71ac7e1a2.png">

Note that `Result.match` there is a wrapper, but I'm calling `require("ts-pattern").match(err)` behind the Intellisense window.

I've definitely got the commit pulled:
<img width="902" alt="Screen Shot 2021-12-15 at 5 57 19 PM" src="https://user-images.githubusercontent.com/1235378/146293872-bc3e44c6-d4a8-4e76-a7dd-cb6555771236.png">

And `require.resolve` is reporting the link is working:
<img width="892" alt="Screen Shot 2021-12-15 at 5 58 10 PM" src="https://user-images.githubusercontent.com/1235378/146293970-507fce67-840a-49a1-9cea-509fca6c0f73.png">

**Comment by gvergnaud** [comment]
Here is your own codesandbox example using the prerelease including the fix (`3.3.4-rc.0`): https://codesandbox.io/s/mystifying-mcclintock-53fhk?file=/src/index.ts

It seems to fix your issue, but please try it again on your own codebase (make sure you aren't hitting Typescript's cache). IF you still run in the same issue, could you provide another sandbox with a repro case?

**Comment by joshgummersall** [comment]
Huh - fair enough! The codesandbox definitely works as expected, I'll see if I can figure out why VSCode isn't showing me the right Intellisense. Thanks!

**Comment by gvergnaud** [comment]
Oh I see, I think that's because a regular error is structurally assignable to your custom one since all of its properties are optional. I'll see what I can do

**Comment by joshgummersall** [comment]
Makes sense - my use case is maybe unusual. I'm working on implementing https://doc.rust-lang.org/std/result/enum.Result.html in TypeScript, and using `match` to unwrap the ok/err states, and then using `match` again to unwrap the error union. Using and matching on custom errors is meaningful, even if they are all assignable to each other. Anyways, I appreciate your time and effort here! This library is really amazing to use.

**Comment by gvergnaud** [comment]
Ok this time I think I fixed it for real ;) https://codesandbox.io/s/eloquent-feather-u1zvj?file=/src/index.ts you can try the latest RC and if that works for you I'll turn it in a patch version

**Comment by joshgummersall** [comment]
Looks great, @gvergnaud! Thanks again for all your time & effort.

**Comment by gvergnaud** [comment]
Released in v3.3.4
